
TOP = test___PROJECT-NAME__
SRC = __PROJECT-NAME__.v
TEST_SRC= test-__PROJECT-NAME__.v
BIN = $(TOP).vvp

$(BIN): $(SRC) $(TEST_SRC)
	iverilog -o $(BIN) -s $(TOP) $(SRC) $(TEST_SRC)

.PHONY: all clean test

all: $(BIN)

test: $(BIN)
	vvp $(BIN)

clean:
	rm -f *.vvp *.vcd

